version: '3.1'

services:
  db:
    image: postgres:14.6-alpine
    restart: always
    ports:
      - '5432:5432'
    environment: 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: teslodb
    volumes:
      - ./postgres:/var/lib/postgresql/data
